"""
Build TestPlan from AuditRequest: baseUrl and routes to visit.
"""
from typing import List

from .schemas import AuditRequest, ProjectInfo, RoutePlan, TestPlan


def build_test_plan(request: AuditRequest) -> TestPlan:
    """Build a TestPlan from an AuditRequest."""
    project = ProjectInfo(
        name="Autogenerated plan",
        framework="nextjs",
        baseUrl=request.baseUrl,
        notes="Visit each route and report specific good points and problems.",
    )
    routes: List[RoutePlan] = []
    for raw_path in (request.routes or ["/"]):
        path = raw_path or "/"
        if not path.startswith("/"):
            path = f"/{path}"
        purpose = "Landing page" if path == "/" else "Content page"
        routes.append(RoutePlan(path=path, purpose=purpose))
    return TestPlan(
        project=project,
        standards=["Nielsen", "WCAG2.2_AA", "Performance", "Responsive", "HTTPS"],
        routes=routes,
    )
